### ISSUE TITLE
Display RPM of Shooter

### ISSUE THREAD

**Issue by Parsia-8001** [FRC5549Robotics/5549-2020#1]
Read RPM of the motors connected to the 4 Talon SRXs using the mag encoder. The Talon SRXs are wired up to the CAN bus.

**Comment by Parsia-8001** [comment]
Currently build is working on the shooter prototype and electrical is adding extensions for various sensors and wiring up the TalonSRXs. As soon as that is done, we will get started with trying to read RPM from the mag encoders that are connected to the Talon SRXs.

**Comment by Parsia-8001** [comment]
Mechanical has finished with the shooter and tomorrow we will attach it to the practice bot, Tom, to test out reading rpm. From the short amount of time available to test the prototype, we weren't able to get exact rpm but we received quadrature position data from one of the encoders.

**Comment by Parsia-8001** [comment]
On Saturday, February 8th, we were able to display RPM and velocity from the mag encoders connected to the shooter motors. The issue was the ribbon cables were not working and thus an **electrical team** problem :) 

Next steps is to apply a preliminary PID loop to be able to reach the specific RPM set points.

**Comment by dylantknguyen** [comment]
Fixed in commit bfb1bbc
