### ISSUE TITLE
Adding Video from Limelight to Dashboard

### ISSUE THREAD

**Issue by dylantknguyen** [FRC5549Robotics/5549-2020#11]
The Limelight camera feed should be added to the dashboard so that the operator can easily see the target. The attached thread has details on it.

https://www.chiefdelphi.com/t/how-to-show-limelight-camera-on-smartdashboard-shuffleboard/375092

**Comment by Parsia-8001** [comment]
All we need is a USB type A to USB type A cable and it will show up. A USB type A to type B (printer cable) works too but I'd rather not block the port that is used to flash radio and emergency deploy.

**Comment by JimTheScientist** [comment]
The feed is on ShuffleBoard.
