### ISSUE TITLE
Loading and Indexing of Power Cells

### ISSUE THREAD

**Issue by dylantknguyen** [FRC5549Robotics/5549-2020#25]
# Loading Power Cells
Ok so when loading power cells off of the ground we need to run:
- Intake
- Both sides of vertical indexer, one in opposing direction of the other
- Horizontal Indexer
- Horizontal piece and semicircle (Same motor)
- Shooter with bottom wheels in direction of shooting and top wheels rotating in the opposite direction of shooting 

   - This lets the balls in the semicircle continue to spin and not get stuck by coming in contact with the static sticky shooter wheels

# Indexing while <oving
When not actively intaking balls, we need to continue to run everything in the loading power cells section but run the intake in reverse to push any power cells in our way to prevent overloading on cells or getting them stuck under the bot. Eventually this indexing should stop when we count that we have enough balls in the semicircle (around 4) that will be counted with a color sensor or ultrasonic in the horizontal piece.

# Shooting Sequence
Because a ball will be "Stuck" in the shooter from the indexing loading, we need to remove this. So first the horizontal piece/semicircle and shooter have to be run in reverse for a very short period of time, just enough to consistently keep a ball out of the shooter wheels. Then, the shooter has to be spooled up to the proper rpm. After all this is set, run the semicircle/horizontal piece and indexer system forward shooting balls out of the shooter. We might need to look into how fast we can shoot balls out without losing an appreciable amount of RPM on the shooter motors as to maximize shooting speed while maintaining accuracy in shooter heights.

**Comment by dylantknguyen** [comment]
# Indexer Ideas
- Three Sensors (One per "Average"/Middle Location)
- If all three sensors see the balls, stop semicircle and indexer but continue allowing intake on the button (OVERRIDE DPAD BUTTON)
- Once the shooter button is pressed shoot 3 balls while loading 2 then shoot 2. Reset to default when done.

**Comment by tulser** [comment]
> 
> # Indexer Ideas
> 
>     * Three Sensors (One per "Average"/Middle Location
> 
>     * If all three sensors see the balls, stop semicircle and indexer but continue allowing intake on the button (OVERRIDE DPAD BUTTON)
> 
>     * Once the shooter button is pressed shoot 3 balls while loading 2 then shoot 2. Reset to default when done.

Mostly agree except for this:
>     * Once the shooter button is pressed shoot 3 balls while loading 2 then shoot 2. Reset to default when done.

I think we should have a button reserved for firing one ball at a time OR what we could do is have a tap or press to fire one and then a hold to fire multiple. I know how the second option can be implemented.

**Comment by dylantknguyen** [comment]
Implemented in 9ffa21a. Will add a color sensor to perfect.

**Comment by dylantknguyen** [comment]
Implemented with a color sensor in a7b8c53. Now, it is able to detect balls attempting to enter the semicircle and count the amount of balls in the semicircle
