### ISSUE TITLE
Standard baseline for code structure

### ISSUE THREAD

**Issue by dylantknguyen** [FRC5549Robotics/5549-2020#4]
Meeting on Saturday (1/18) discussing code structure and best practices. Figure out an effective baseline for the structure of the code to follow through the entire season.

**Comment by Parsia-8001** [comment]
We discussed a new software architecture that is similar to command-based programming. It would be great if we could move away from our traditional structure and divide components into their specific classes. For example, we would have a shooter class that has functions like long shooter and low shooter.

**Comment by dylantknguyen** [comment]
# Functions / Code Structures

## Drive
`turnToAngle(angle)`
`changeGear()`
`setSpeed(percent)` Depends on Driver Controller
## Intake 
`takeIn()`
`eject()`
## Indexer
`forward()`
`reverse()`
## Shooter
`shootFar()`
`shootMid()`
`shootShort()`
`shootAuto(distance)`
`initializeShooter()` Add to shoot functions
## Lift 
`dropDown()`
`liftUp()`
`runMotor(power)` Fixed Value or Variable Power depending on Operator Controller
## Vision
`getDistance()`
`getAngle()`
## Robot
# Wanted Features

## Driver

## Operator

## Dashboard
- Camera
- Battery Voltage
- Drive Train Gear

**Comment by Parsia-8001** [comment]
I really like the structure. Today I streamlined the structure you made further and made sure commenting and naming were standardized as well as the methods. Got rid of many errors too in the process. All we need to figure out is how to connect to the other files from robot.py and make sure the methods are being recognized.

**Comment by dylantknguyen** [comment]
We have figured out the code structure. It is working as of commit 6d2183c25863968ef448dc0b84b4db548a4a1c55.
